require("postmac.plugins-setup")
require("postmac.core.options")
require("postmac.core.keymaps")
require("postmac.core.colorscheme")
require("postmac.plugins.comment")
require("postmac.plugins.nvim-tree")
require("postmac.plugins.lualine")
require("postmac.plugins.telescope")
